server:
  port: 80
#debug: true
spring:
  batch:
    job:
      enabled: true
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/dataim
    username: root 
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 10 
#      aop-patterns: com.* 
      time-between-log-stats-millis: 3000000000 
      filter:
        log4j:
          enabled: true 
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:  
      max-file-size:  300MB
      max-request-size: 300MB
  mvc:
    staticPathPattern: /**
  devtools:
    restart:
      additional-exclude: src/main/resources/static/html/user/**
mybatis:
  type-aliases-package: com.data;com.zxt
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/**/*-mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
import:
  path: d:/upload/data/
