
server:
  port: 80
spring:
  datasource:
    #url: jdbc:mysql://123.206.72.111:3306/springmvc
    url: jdbc:mysql://114.67.227.246:3306/springmvc
    username: grelove
    password: grelove
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 10 
      aop-patterns: com.qian.springmvc.modules.* 
      time-between-log-stats-millis: 3000000000 
      filter:
        log4j:
          enabled: true 
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:  
      max-file-size:  30MB
      max-request-size: 30MB
  mvc:
    staticPathPattern: /**
  devtools:
    restart:
      additional-exclude: src/main/resources/static/html/user/**
  redis:
    host: 114.67.227.246 
    port: 6379
    password: 12345687
mybatis:
  type-aliases-package: com.qian
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/**/*-mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
